### ISSUE TITLE
App crashes on Apple monteray - crash report points to electron

### ISSUE THREAD

**Issue by reuvenneumann** [zachrattner/scourhead#8]
The crash report specifically mentions Electron:
Process:               Scourhead [1823]
Path:                  /Applications/Scourhead.app/Contents/MacOS/Scourhead
Identifier:            com.zachrattner.scourhead
Version:               1.0.1 (1.0.1)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               503

Date/Time:             2024-12-31 10:06:09.6099 +0200
OS Version:            macOS 12.7.6 (21H1320)
Report Version:        12
Bridge OS Version:     3.0 (14Y910)
Anonymous UUID:        CB8C375F-842D-B812-15E4-4F38B015E15A

Time Awake Since Boot: 340 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [1823]

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   Electron Framework            	       0x11e372adf ares_dns_rr_get_name + 28682239
1   Electron Framework            	       0x11e36a11c ares_dns_rr_get_name + 28646972
2   Electron Framework            	       0x11a5d2780 node::GetEnvironmentIsolateData(node::Environment*) + 7845696
3   Electron Framework            	       0x11a5d26dd node::GetEnvironmentIsolateData(node::Environment*) + 7845533
4   Electron Framework            	       0x11a92e971 node::AsyncResource::get_trigger_async_id() const + 311457
5   Electron Framework            	       0x11e36ea38 ares_dns_rr_get_name + 28665688
6   Electron Framework            	       0x11a92e861 node::AsyncResource::get_trigger_async_id() const + 311185
7   Electron Framework            	       0x11a7e1fa9 v8::CppHeap::CollectGarbageInYoungGenerationForTesting(cppgc::EmbedderStackState) + 301833
8   Electron Framework            	       0x11a73ac31 v8::Unwinder::PCIsInV8(unsigned long, v8::MemoryRange const*, void*) + 136865
9   Electron Framework            	       0x11a73bcb9 v8::Unwinder::PCIsInV8(unsigned long, v8::MemoryRange const*, void*) + 141097
10  Electron Framework            	       0x11ad01204 v8::internal::TickSample::print() const + 713972
11  Electron Framework            	       0x11a5fb653 v8::Isolate::Initialize(v8::Isolate*, v8::Isolate::CreateParams const&) + 259
12  Electron Framework            	       0x11e5634ec ares_dns_rr_get_name + 30716428
13  Electron Framework            	       0x11915e07f v8::BackingStore::MaxByteLength() const + 190463
14  Electron Framework            	       0x119141327 v8::BackingStore::MaxByteLength() const + 72359
15  Electron Framework            	       0x11b926dc4 v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord(v8::internal::compiler::MapRef, v8::internal::compiler::MapRef, v8::internal::InternalIndex, v8::internal::compiler::ObjectRef) const + 7544628
16  Electron Framework            	       0x11b92a63a v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord(v8::internal::compiler::MapRef, v8::internal::compiler::MapRef, v8::internal::InternalIndex, v8::internal::compiler::ObjectRef) const + 7559082
17  Electron Framework            	       0x11b9264d8 v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord(v8::internal::compiler::MapRef, v8::internal::compiler::MapRef, v8::internal::InternalIndex, v8::internal::compiler::ObjectRef) const + 7542344
18  Electron Framework            	       0x1193e8a3e v8::CodeEvent::GetScriptLine() + 546062
19  Electron Framework            	       0x1193e9a4d v8::CodeEvent::GetScriptLine() + 550173
20  Electron Framework            	       0x1193e98a8 v8::CodeEvent::GetScriptLine() + 549752
21  Electron Framework            	       0x1193e82ca v8::CodeEvent::GetScriptLine() + 544154
22  Electron Framework            	       0x1193e83b2 v8::CodeEvent::GetScriptLine() + 544386
23  Electron Framework            	       0x119048765 ElectronMain + 245
24  dyld                          	       0x10e4c552e start + 462

**Comment by zachrattner** [comment]
Thanks @reuvenneumann let me test this out and I can bring this into main after testing.  Appreciate the help!
